const colors={
    BLACK:'#000',
    WHITE:'#FFF',
    GRAY:'#808080',
    GREEN:'#008000',
    DODGER_BLUE:'#428AF8',
    SILVER:'#BEBEBE',
    TORCH_RED:'F8262F',
    MISCHKA:'#E5E4E6',
    TOMATO:'tomato',
    NAVY:'navy',
    TRANSPARENT:'transparent',

    SUCCESS:'#66C067',
    DANGER:'#DD5E5A',

    HEADER:'#000',

    ICON_ACTIVE_COLOR:'tomato',
    ICON_COLOR:'gray',


    //HOME
    ITEM_CONTAINER_COLOR:'#D3D9E6',
    ITEM_GRADIENT_START_COLOR:'#8693AB',
    ITEM_GRADIENT_END_COLOR:'#BDD4E7',

    //DIARY
    ITEM_GRADIENT_SERVICEBILL_COMPLETE_START_COLOR:'#cfd9df',
    ITEM_GRADIENT_SERVICEBILL_COMPLETE_END_COLOR:'#e2ebf0',
    ITEM_GRADIENT_SERVICEBILL_DONE_START_COLOR:'#F5F7FA',
    ITEM_GRADIENT_SERVICEBILL_DONE_END_COLOR:'#C3CFE2',
}

export default colors;